# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'k_giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 348)
        Form.setStyleSheet("background-color: rgb(48, 13, 47);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 251, 281))
        self.label.setStyleSheet("background-color:rgb(66, 64, 66);border-radius:30px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"background-color:rgb(66, 64, 66);")
        self.label_2.setObjectName("label_2")
        self.lnad = QtWidgets.QLineEdit(Form)
        self.lnad.setGeometry(QtCore.QRect(80, 120, 171, 31))
        self.lnad.setStyleSheet("background-color:rgb(29,37,97);border:none;border-radius:15px;color:white;padding-left:10px;padding-right:10px;\n"
"")
        self.lnad.setText("")
        self.lnad.setObjectName("lnad")
        self.lnsifre = QtWidgets.QLineEdit(Form)
        self.lnsifre.setGeometry(QtCore.QRect(80, 170, 171, 31))
        self.lnsifre.setStyleSheet("background-color:rgb(29,37,97);border:none;border-radius:15px;color:white;padding:10px;padding-right:10px;\n"
"")
        self.lnsifre.setText("")
        self.lnsifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnsifre.setObjectName("lnsifre")
        self.pushButtongiris = QtWidgets.QPushButton(Form)
        self.pushButtongiris.setGeometry(QtCore.QRect(130, 230, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtongiris.setFont(font)
        self.pushButtongiris.setStyleSheet("QPushButton{color:white;border:none;border-radius:20px;}\n"
"QPushButton::hover{background-color:black;}")
        self.pushButtongiris.setObjectName("pushButtongiris")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "KULLANICI GİRİŞ SAYFASI"))
        self.pushButtongiris.setText(_translate("Form", "GİRİŞ"))
